name: infra_check

on:
  push:
    branches:
      - main

jobs:
  build_and_load:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          WORK_FOLDER: "/root/custom_checks/"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          envs: WORK_FOLDER
          script: |
            cd $WORK_FOLDER
            sudo git pull
            sudo ls -l $WORK_FOLDER
            sudo tar --exclude=./venv --exclude=./.git* -cvf infra_check.tar .
            sudo curl -X POST -F 'file_path=infra_check.tar' -F 'file=@infra_check.tar' http://localhost:8889/upload

  get_modified_data:
    needs: build_and_load
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do echo "changed file: ${changed_file}."; done

  send_message:
    runs-on: ubuntu-latest
    needs: build_and_load
    steps:
      - name: Send message to person R
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_R_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}. 
            Changes: ${{ steps.files.outputs.all }}.


      - name: Send message to person N
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_N_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}. Modified files: ${{ github.event.head_commit.modified }}. Added Files: ${{ github.event.head_commit.added }}. Deleted Files: ${{ github.event.head_commit.removed }}


      - name: Send message to person O
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_O_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}. Modified files: ${{ github.event.head_commit.modified }}. Added Files: ${{ github.event.head_commit.added }}. Deleted Files: ${{ github.event.head_commit.removed }}
            
            
            
            
            
