name: infra_check

on:
  push:
    branches:
      - main

jobs:

  get_all_modified_files_and_send_messages:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
  
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was changed"
          done

      - name: Send message to person R
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_R_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Commit message:
            ${{ github.event.head_commit.message }}
            Added files:
            ${{ steps.changed-files.outputs.added_files }}
            Modified files:
            ${{ steps.changed-files.outputs.modified_files }}
            Deleted files:
            ${{ steps.changed-files.outputs.deleted_files }}
            Download new infra_check.tar in a browser via link:
            http://${{ secrets.HOST }}/my_storage/download/icar.tar

      - name: Send message to person N
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_N_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Commit message:
            ${{ github.event.head_commit.message }}
            Added files:
            ${{ steps.changed-files.outputs.added_files }}
            Modified files:
            ${{ steps.changed-files.outputs.modified_files }}
            Deleted files:
            ${{ steps.changed-files.outputs.deleted_files }}
            Donwload new infra_check.tar in a browser via link:
            http://${{ secrets.HOST }}/my_storage/download/icar.tar

      - name: Send message to person O
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_O_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Commit message:
            ${{ github.event.head_commit.message }}
            Added files:
            ${{ steps.changed-files.outputs.added_files }}
            Modified files:
            ${{ steps.changed-files.outputs.modified_files }}
            Deleted files:
            ${{ steps.changed-files.outputs.deleted_files }}
            Download new infra_check.tar in a browser via link:
            http://${{ secrets.HOST }}/my_storage/download/icar.tar


  build_and_load:
    runs-on: ubuntu-latest
    environment: aws
    needs: get_all_modified_files_and_send_messages
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            export WD=/home/$USER/infra_check
            cd "$WD"
            git pull
            rm icar.tar
            rm -rf "$WD/dist"
            make build
            tar -cvf icar.tar README.md infra.conf ./dist/icarus-* ./deb1*
            curl -X POST -F path=icar.tar -F file=@icar.tar http://${{ secrets.HOST }}/api/upload