name: infra_check

on: [push]

jobs:
  build and load:
    runs-on: debian-latest
    environment: aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.HOST_USER }}
          key: ${{ env.HOST_SSH_KEY }}
          script: |
            cd custom_checks/
            git pull
            tar --exclude=./venv --exclude=./.git* -cvf infra_check.tar .
            curl -X POST -F 'file_path=infra_check.tar' -F 'file=@infra_check.tar' http://localhost:8889/upload

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message to person R
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_R_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Modified files:
            ${{ github.event.head_commit.modified }}
            Added Files:
            ${{ github.event.head_commit.added }}
            Deleted Files:
            ${{ github.event.head_commit.removed }}

      - name: Send message to person N
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_N_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Modified files:
            ${{ github.event.head_commit.modified }}
            Added Files:
            ${{ github.event.head_commit.added }}
            Deleted Files:
            ${{ github.event.head_commit.removed }}

      - name: Send message to person O
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_O_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Modified files:
            ${{ github.event.head_commit.modified }}
            Added Files:
            ${{ github.event.head_commit.added }}
            Deleted Files:
            ${{ github.event.head_commit.removed }}
