name: infra_check

on:
  push:
    branches:
      - main

jobs:
  build_and_load:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          WORK_FOLDER: "infra_check"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          envs: WORK_FOLDER
          script: |
            cd $WORK_FOLDER
            git pull
            ls -l $WORK_FOLDER
            tar --exclude=./venv --exclude=./.git* -cvf infra_check.tar .
            curl -X POST -F 'path=infra_check.tar' -F 'file=@infra_check.tar' http://localhost:8889/upload


  get_all_modified_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    needs: build_and_load
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          since_last_remote_commit: true 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was changed"
          done > $GIT_MODIFIED_FILES_LIST

      - name: Send message to person R
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_R_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Modified files:
            ${{ steps.changed-files.outputs.GIT_MODIFIED_FILES_LIST }}

      - name: Send message to person N
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_N_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Modified files:
            ${{ steps.changed-files.outputs.GIT_MODIFIED_FILES_LIST }}

      - name: Send message to person O
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PERSON_O_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Test of ${{ github.workflow }} created by ${{ github.actor }}.
            Modified files:
            ${{ steps.changed-files.outputs.GIT_MODIFIED_FILES_LIST }}
